### ISSUE TITLE
Single-Veteran Tabbed content not working

### ISSUE THREAD

**Issue by kjroelke** [choctaw-nation/veterans-archive#20]
Tabs get "hung" on random indices and stop working.
Live example: https://cnoveterandev.wpenginepowered.com/veteran/tray-ardese/

**Comment by blake-perkins-dev** [comment]
It appears to be the div that appears before the button (with class of btn-lower) that is causing this issue. It also has nav-link and active on it which are interfering with it being able to target the button properly.

I removed the nav-link and active classes from the div which appears before the button and it works without issue (although, the styling for the button doesn't appear correctly now).

I haven't pushed any changes because this will require a styling fix to be fully solved, but this should be the fix.
